spring.application.name=gateway-service
server.port=8888
# eureka client configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

## Enable Eureka Based routing(dynamic routing) in Spring Cloud Gateway
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# routes

# doctor_patient_demo route
spring.cloud.gateway.server.webmvc.routes[0].id=doctor_patient_demo
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://doctor_patient_demo
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/**

# openfeign-service route
spring.cloud.gateway.server.webmvc.routes[1].id=openfeign-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://openfeign-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/feign/**

# embedded-document-demo route
spring.cloud.gateway.server.webmvc.routes[2].id=embeddeddocumentdemo
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://embeddeddocumentdemo
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v2/**

# actuator configuration
management.endpoints.web.exposure.include=*
